#!/usr/bin/env bash

### FILE AUTOMATICALLY TANGLED FROM ~/.config/shell-config.org ###

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo
error)" "$(history|tail -n1|sed -e
'\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias c='clear'
alias up='sudo apt-fast update'
alias ug='sudo apt-fast upgrade'

# TODO install exa, look into if it affects dired
# alias ls="exa -lh"

alias vcon='sudo surfshark-vpn attack'
alias vdis='sudo surfshark-vpn down'
