#! /bin/sh

# caching wallpaper for lock screen
WALL="$(find $HOME/.local/share/wallpapers -type f | shuf -n1)"
RES=$(xrandr | grep '\*' | awk '{print $1}')!
convert "$WALL" -resize $RES /tmp/lockpaper.png

# AUTOSTART PROGRAMS ##########################################################
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x pcmanfm >/dev/null || pcmanfm -d &
# nm-applet &
udiskie &
compton --backend glx --vsync opengl-swc &
usr/lib/xfce-polkit/xfce-polkit &
nitrogen --random --set-zoom-fill &
xss-lock --transfer-sleep-lock -- i3lock --nofork --image /tmp/lockpaper.png &

$HOME/.local/bin/scripts/polybar/polybar-launch.sh &
pgrep -x battery-checker >/dev/null || $HOME/.local/bin/scripts/utility/battery-checker &
# END AUTOSTART PROGRAMS ######################################################

# switch caps to ctrl
setxkbmap -option ctrl:nocaps

# BSPWM CONFIG ################################################################
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

# make the right side take up more than the left side by default
bspc config split_ratio 0.46
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# END BSPWM CONFIG ############################################################
