#!/bin/sh

. ~/.config/shell/env_vars

# BSPWM CONFIG ################################################################
# TODO: adjust this to make a bit more elegant and also to work for hot plugging my laptop into things as well
# ~/.local/bin/scripts/utility/handle-monitors &
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.46

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme spiral

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Kupfer.py focus=on
# FIXME: these two don't seem to work right
# bspc rule -a blueman-manager state=floating
# bspc rule -a pavucontrol state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
# END BSPWM CONFIG ############################################################
# also check out ~/.dotfiles/.config/sxhkd/sxhkdrc

# GENERAL SETTINGS ############################################################
# switch caps to ctrl
setxkbmap -option ctrl:nocaps &

# make sure i dont see a weird 'X' for cursor
xsetroot -cursor_name left_ptr &
# END GENERAL SETTINGS ########################################################

# AUTOSTART PROGRAMS ##########################################################
_run() {
    if ! pgrep -x "${1}" >/dev/null; then
        "$@" &
    fi
}

_run sxhkd -t 2
_run pcmanfm -d
_run battery-checker
_run dunst
_run redshift -l 41.87811:-87.62980
_run syncthing --allow-newer-config
_run start-searxng
if [ "$(hostname)" != "lake-michigan" ]; then
    # TODO: switch to a lemonbar-based setup eventually
    pgrep -x polybar >/dev/null || polybar &
fi

(
    pkill picom
    sleep .5
    picom
) &
/usr/lib/xfce-polkit/xfce-polkit &
# END AUTOSTART PROGRAMS ######################################################

# WALLPAPERS ##################################################################
# caching wallpaper for lock screen. first look for a favorite-wallpaper.jpg or
# .png in ~/, otherwise pick a random one
WALL_DIR=~/Pictures/wallpapers/
LOCKSCREEN_PAPER="$(find $WALL_DIR -type f | shuf -n1)"
DESKTOP_PAPER=~/favorite-wallpaper.png
[ ! -e "$DESKTOP_PAPER" ] && DESKTOP_PAPER=~/favorite-wallpaper.jpg
[ ! -e "$DESKTOP_PAPER" ] && DESKTOP_PAPER="$(find $WALL_DIR -type f | shuf -n1)"

# setting wallpaper and lockpaper
RES=$(xrandr | grep '\*' | awk '{print $1}')!
convert "$LOCKSCREEN_PAPER" -resize $RES /tmp/lockpaper.png
xwallpaper --zoom "$DESKTOP_PAPER" &
xss-lock --transfer-sleep-lock -- i3lock --nofork --image /tmp/lockpaper.png &

# expose desktop paper and lockpaper in case you want to know their paths
(
    echo DESKTOP_PAPER="\"$DESKTOP_PAPER\"" >/tmp/whats-the-wallpaper.txt
    echo LOCKSCREEN_PAPER="\"$LOCKSCREEN_PAPER\"" >>/tmp/whats-the-wallpaper.txt
) &

# TODO:
# - get wal set up and then use that leter to config the border color for
#   inactive and active windows
# END WALLPAPERS ##############################################################
